apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: testlb
  name: web
  namespace: testlb
spec:
  containers:
  - image: nginx:latest
    name: web
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
