apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testapp
  name: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - image:  acrunir.azurecr.io/unir:737fec53
        name: testapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
      imagePullSecrets:
      - name: registry-credentials