apiVersion: v1
data:
  .dockerconfigjson: "eyJhdXRocyI6eyJhY3J1bmlyLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJhY3J1bmlyIiwicGFzc3dvcmQiOiJlam9JZGhCeU1qVkd1QytETW9hQkVBTkltby9ialVJdmx2WkRNN0ZNNG4rQUNSQnZiMVhvIiwiYXV0aCI6IllXTnlkVzVwY2pwbGFtOUpaR2hDZVUxcVZrZDFReXRFVFc5aFFrVkJUa2x0Ynk5aWFsVkpkbXgyV2tSTk4wWk5ORzRyUVVOU1FuWmlN
Vmh2In19fQ==" 
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: wp
type: kubernetes.io/dockerconfigjson